### ISSUE TITLE
发生了错误（使用的v3api）

### ISSUE THREAD

**Issue by wuwo020** [tediorelee/koishi-plugin-youtube#1]
“你好，可以为这个插件写一份帮助文档吗？在我配置成功后，我看到了API得到了回应，但是我这里提示错误，错误信息如下：'发生错误!;  TypeError: Cannot read properties of undefined (reading 'length')'

**Comment by tediorelee** [comment]
> “你好，可以为这个插件写一份帮助文档吗？在我配置成功后，我看到了API得到了回应，但是我这里提示错误，错误信息如下：'发生错误!;  TypeError: Cannot read properties of undefined (reading 'length')'

刚收到提醒，我明天白天完善下流程文档，顺便可以提供下你的视频链接吗？我拿来测试用

**Comment by wuwo020** [comment]
我是随便在youtube上随意寻找了三个链接都没有成功，就以这个链接为例吧：https://youtu.be/8yveF9B6lvA
&nbsp;


1602169603
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月11日(星期天) 凌晨0:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tediorelee/koishi-plugin-youtube] 发生了错误（使用的v3api） (Issue #1)






“你好，可以为这个插件写一份帮助文档吗？在我配置成功后，我看到了API得到了回应，但是我这里提示错误，错误信息如下：'发生错误!;  TypeError: Cannot read properties of undefined (reading 'length')'

刚收到提醒，我明天白天完善下流程文档，顺便可以提供下你的视频链接吗？我拿来测试用

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by tediorelee** [comment]
> 我是随便在youtube上随意寻找了三个链接都没有成功，就以这个链接为例吧：https://youtu.be/8yveF9B6lvA
> 
> &nbsp;
> 
> 
> 
> 
> 
> 1602169603
> 
> ***@***.***
> 
> 
> 
> 
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人: ***@***.***&gt;; 
> 
> 发送时间: 2022年12月11日(星期天) 凌晨0:11
> 
> 收件人: ***@***.***&gt;; 
> 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 
> 主题: Re: [tediorelee/koishi-plugin-youtube] 发生了错误（使用的v3api） (Issue #1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> “你好，可以为这个插件写一份帮助文档吗？在我配置成功后，我看到了API得到了回应，但是我这里提示错误，错误信息如下：'发生错误!;  TypeError: Cannot read properties of undefined (reading 'length')'
> 
> 
> 
> 刚收到提醒，我明天白天完善下流程文档，顺便可以提供下你的视频链接吗？我拿来测试用
> 
> 
> 
> —
> 
> 直接回复此邮件，在GitHub上查看，或取消订阅.
> 
> ***@***.***与&gt;.

好的没问题，明天我测试一下再回复

**Comment by tediorelee** [comment]
> 

找了一下原因，原来是因为这个视频链接解析出来，不带有tags这个东西，我之前测试的视频链接都是有的，所以代码上报错了，会修改一下更新

**Comment by wuwo020** [comment]
好的，辛苦了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 中午1:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tediorelee/koishi-plugin-youtube] 发生了错误（使用的v3api） (Issue #1)




   
找了一下原因，原来是因为这个视频链接解析出来，不带有tags这个东西，我之前测试的视频链接都是有的，所以代码上报错了，会修改一下更新

**Comment by tediorelee** [comment]
> 

readme和代码都更新了，但是不确定同步到koishi插件那边需要多久，晚点再试试，thanks
